### ISSUE TITLE
Build version is not required on the ABS Server

### ISSUE THREAD

**Issue by GrakovNe** [GrakovNe/lissen-android#66]
Stacktrace from Acra:

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.grakovne.lissen.channel.common.ConnectionInfo.<init>, parameter buildNumber
	at org.grakovne.lissen.channel.common.ConnectionInfo.<init>(Unknown Source:12)
	at org.grakovne.lissen.channel.audiobookshelf.common.converter.ConnectionInfoResponseConverter.apply(ConnectionInfoResponseConverter.kt:11)
	at org.grakovne.lissen.channel.audiobookshelf.common.AudiobookshelfChannel$fetchConnectionInfo$2.invokeSuspend(AudiobookshelfChannel.kt:65)
	at org.grakovne.lissen.channel.audiobookshelf.common.AudiobookshelfChannel$fetchConnectionInfo$2.invoke(Unknown Source:8)
	at org.grakovne.lissen.channel.audiobookshelf.common.AudiobookshelfChannel$fetchConnectionInfo$2.invoke(Unknown Source:4)
	at org.grakovne.lissen.channel.common.ApiResult.map(ApiResult.kt:29)
	at org.grakovne.lissen.channel.audiobookshelf.common.AudiobookshelfChannel.fetchConnectionInfo$suspendImpl(AudiobookshelfChannel.kt:65)
	at org.grakovne.lissen.channel.audiobookshelf.common.AudiobookshelfChannel$fetchConnectionInfo$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c23185f, Dispatchers.Main.immediate]
```

**Comment by GrakovNe** [comment]
Fixed in https://github.com/GrakovNe/lissen-android/releases/tag/1.1.12
