### ISSUE TITLE
App is crashing when cached book incomplete

### ISSUE THREAD

**Issue by GrakovNe** [GrakovNe/lissen-android#80]
Stacktrace:

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at org.grakovne.lissen.content.cache.LocalCacheRepository.fetchBook(LocalCacheRepository.kt:129)
	at org.grakovne.lissen.content.cache.LocalCacheRepository$fetchBook$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)

**Comment by GrakovNe** [comment]
fixed in: https://github.com/GrakovNe/lissen-android/releases/tag/1.1.20
