### ISSUE TITLE
App crashes when no next media item found

### ISSUE THREAD

**Issue by GrakovNe** [GrakovNe/lissen-android#82]
Stacktrace: 

java.lang.StackOverflowError: stack size 8188KB
	at java.util.Arrays.binarySearch(Arrays.java:1707)
	at androidx.media3.common.util.Util.binarySearchFloor(Util.java:1283)
	at androidx.media3.exoplayer.PlaylistTimeline.getChildIndexByWindowIndex(PlaylistTimeline.java:83)
	at androidx.media3.exoplayer.AbstractConcatenatedTimeline.getWindow(AbstractConcatenatedTimeline.java:198)
	at androidx.media3.common.Timeline.getWindow(Timeline.java:1087)
	at androidx.media3.common.BasePlayer.getMediaItemAt(BasePlayer.java:352)
	at org.grakovne.lissen.playback.service.PlaybackNotificationService.findAvailableTrackIndex(PlaybackNotificationService.kt:51)

**Comment by GrakovNe** [comment]
fixed in https://github.com/GrakovNe/lissen-android/releases/tag/1.1.21
